export const DEFAULT_SOURCE_PREFETCH_ENABLED = true;
export const DEFAULT_SOURCE_PREFETCH_INTERVAL_MINUTES = 60;
export const MIN_SOURCE_PREFETCH_INTERVAL_MINUTES = 5;
export const MAX_SOURCE_PREFETCH_INTERVAL_MINUTES = 7 * 24 * 60;
